In [587]:
import numpy as np

In [589]:
v = np.array([2, 4, 6])

v

array([2, 4, 6])

In [591]:
u = np.array([2, 4, 6])

u

array([2, 4, 6])

In [593]:
v.shape

(3,)

In [595]:
u.shape

(3,)

In [597]:
V = np.array([[2, 4, 6], [3, 6, 9], [4, 8, 12]])

V

array([[ 2,  4,  6],
       [ 3,  6,  9],
       [ 4,  8, 12]])

In [599]:
U = np.array([[2, 4, 6], [3, 6, 9], [4, 8, 12]])

U

array([[ 2,  4,  6],
       [ 3,  6,  9],
       [ 4,  8, 12]])

In [601]:
V.shape

(3, 3)

In [603]:
U.shape

(3, 3)

| #  | NumPy Solution            | Einstein Summation Notation      | Description                                                    |
|----|---------------------------|----------------------------------|----------------------------------------------------------------|
| 1  | `v`                       | `np.einsum("i", v)`              | Returns a view of `v` vector                                   |
| 2  | `np.sum(v)`               | `np.einsum("i->", v)`            | Sums the values of `v` vector                                  |
| 3  | `v * u`                   | `np.einsum("i,i->i", v, u)`      | Element-wise multiplication of `v` and `u` vectors             |
| 4  | `np.inner(v, u)`          | `np.einsum("i,i", v, u)`         | Inner product of `v` and `u` vectors                           |
| 5  | `np.outer(v, u)`          | `np.einsum("i,j->ij", v, u)`     | Outer product of `v` and `u` vectors                           |
| 6  | `V`                       | `np.einsum("ij", V)`             | Returns a view of `V` matrix                                   |
| 7  | `V.T`                     | `np.einsum("ij->ji", V)`         | View transpose of `V` matrix                                   |
| 8  | `np.diag(V)`              | `np.einsum("ii->i", V)`          | View main diagonal of `V` matrix                               |
| 9  | `np.trace(V)`             | `np.einsum("ii->", V)`           | Sums main diagonal of `V` matrix                               |
| 10 | `np.sum(V)`               | `np.einsum("ij->", V)`           | Sums the values of `V` matrix                                  |
| 11 | `np.sum(V, axis=0)`       | `np.einsum("ij->j", V)`          | Sum vertically along the columns of `V` matrix                 |
| 12 | `np.sum(V, axis=1)`       | `np.einsum("ij->i", V)`          | Sum horizontally along the rows of `V` matrix                  |
| 13 | `V * U`                   | `np.einsum("ij,ij->ij", V, U)`   | Element-wise multiplication of `V` and `U` matrices            |
| 14 | `V * U.T`                 | `np.einsum("ij,ji->ij", V, U)`   | Element-wise multiplication of `V` and transposed `U` matrices |
| 15 | `np.dot(V, U)`            | `np.einsum("ij,jk->ik", V, U)`   | Matrix multiplication of `V` and `U` matrices                  |
| 16 | `V[:, :, None, None] * U` | `np.einsum("ij,kl->ijkl", V, U)` | Each value of `V` matrix multiplied by `U` matrix              |
| 17 | `V[:, None] * U`          | `np.einsum("ik,jk->ijk", V, U)`  | Each row of `V` matrix multiplied by `U` matrix                |

In [606]:
# 1

a = np.einsum("i", v)
b = v

display(np.array_equal(a, b))

display(a)
display(b)

True

array([2, 4, 6])

array([2, 4, 6])

In [608]:
# 2

a = np.einsum("i->", v)
b = np.sum(v)

display(np.array_equal(a, b))

display(a)
display(b)

True

12

12

In [610]:
# 3

a = np.einsum("i,i->i", v, u)
b = v * u

display(np.array_equal(a, b))

display(a)
display(b)

True

array([ 4, 16, 36])

array([ 4, 16, 36])

In [612]:
# 4

a = np.einsum("i,i", v, u)
b = np.inner(v, u)

display(np.array_equal(a, b))

display(a)
display(b)

True

56

56

In [614]:
# 5

a = np.einsum("i,j->ij", v, u)
b = np.outer(v, u)

display(np.array_equal(a, b))

display(a)
display(b)

True

array([[ 4,  8, 12],
       [ 8, 16, 24],
       [12, 24, 36]])

array([[ 4,  8, 12],
       [ 8, 16, 24],
       [12, 24, 36]])

In [616]:
# 6

a = np.einsum("ij", V)
b = V

display(np.array_equal(a, b))

display(a)
display(b)

True

array([[ 2,  4,  6],
       [ 3,  6,  9],
       [ 4,  8, 12]])

array([[ 2,  4,  6],
       [ 3,  6,  9],
       [ 4,  8, 12]])

In [618]:
# 7

a = np.einsum("ij->ji", V)
b = V.T

display(np.array_equal(a, b))

display(a)
display(b)

True

array([[ 2,  3,  4],
       [ 4,  6,  8],
       [ 6,  9, 12]])

array([[ 2,  3,  4],
       [ 4,  6,  8],
       [ 6,  9, 12]])

In [620]:
# 8

a = np.einsum("ii->i", V)
b = np.diag(V)

display(np.array_equal(a, b))

display(a)
display(b)

True

array([ 2,  6, 12])

array([ 2,  6, 12])

In [622]:
# 9

a = np.einsum("ii->", V)
b = np.trace(V)

display(np.array_equal(a, b))

display(a)
display(b)

True

20

20

In [624]:
# 10

a = np.einsum("ij->", V)
b = np.sum(V)

display(np.array_equal(a, b))

display(a)
display(b)

True

54

54

In [626]:
# 11

a = np.einsum("ij->j", V)
b = np.sum(V, axis=0)

display(np.array_equal(a, b))

display(a)
display(b)

True

array([ 9, 18, 27])

array([ 9, 18, 27])

In [628]:
# 12

a = np.einsum("ij->i", V)
b = np.sum(V, axis=1)

display(np.array_equal(a, b))

display(a)
display(b)

True

array([12, 18, 24])

array([12, 18, 24])

In [630]:
# 13

a = np.einsum("ij,ij->ij", V, U)
b = V * U

display(np.array_equal(a, b))

display(a)
display(b)

True

array([[  4,  16,  36],
       [  9,  36,  81],
       [ 16,  64, 144]])

array([[  4,  16,  36],
       [  9,  36,  81],
       [ 16,  64, 144]])

In [632]:
# 14

a = np.einsum("ij,ji->ij", V, U)
b = V * U.T

display(np.array_equal(a, b))

display(a)
display(b)

True

array([[  4,  12,  24],
       [ 12,  36,  72],
       [ 24,  72, 144]])

array([[  4,  12,  24],
       [ 12,  36,  72],
       [ 24,  72, 144]])

In [634]:
# 15

a = np.einsum("ij,jk->ik", V, U)
b = np.dot(V, U)

display(np.array_equal(a, b))

display(a)
display(b)

True

array([[ 40,  80, 120],
       [ 60, 120, 180],
       [ 80, 160, 240]])

array([[ 40,  80, 120],
       [ 60, 120, 180],
       [ 80, 160, 240]])

In [636]:
# 16

a = np.einsum("ij,kl->ijkl", V, U)
b = V[:, :, None, None] * U

display(np.array_equal(a, b))

display(a)
display(b)

True

array([[[[  4,   8,  12],
         [  6,  12,  18],
         [  8,  16,  24]],

        [[  8,  16,  24],
         [ 12,  24,  36],
         [ 16,  32,  48]],

        [[ 12,  24,  36],
         [ 18,  36,  54],
         [ 24,  48,  72]]],


       [[[  6,  12,  18],
         [  9,  18,  27],
         [ 12,  24,  36]],

        [[ 12,  24,  36],
         [ 18,  36,  54],
         [ 24,  48,  72]],

        [[ 18,  36,  54],
         [ 27,  54,  81],
         [ 36,  72, 108]]],


       [[[  8,  16,  24],
         [ 12,  24,  36],
         [ 16,  32,  48]],

        [[ 16,  32,  48],
         [ 24,  48,  72],
         [ 32,  64,  96]],

        [[ 24,  48,  72],
         [ 36,  72, 108],
         [ 48,  96, 144]]]])

array([[[[  4,   8,  12],
         [  6,  12,  18],
         [  8,  16,  24]],

        [[  8,  16,  24],
         [ 12,  24,  36],
         [ 16,  32,  48]],

        [[ 12,  24,  36],
         [ 18,  36,  54],
         [ 24,  48,  72]]],


       [[[  6,  12,  18],
         [  9,  18,  27],
         [ 12,  24,  36]],

        [[ 12,  24,  36],
         [ 18,  36,  54],
         [ 24,  48,  72]],

        [[ 18,  36,  54],
         [ 27,  54,  81],
         [ 36,  72, 108]]],


       [[[  8,  16,  24],
         [ 12,  24,  36],
         [ 16,  32,  48]],

        [[ 16,  32,  48],
         [ 24,  48,  72],
         [ 32,  64,  96]],

        [[ 24,  48,  72],
         [ 36,  72, 108],
         [ 48,  96, 144]]]])

In [638]:
# 17

a = np.einsum("ik,jk->ijk", V, U)
b = V[:, None] * U

display(np.array_equal(a, b))

display(a)
display(b)

True

array([[[  4,  16,  36],
        [  6,  24,  54],
        [  8,  32,  72]],

       [[  6,  24,  54],
        [  9,  36,  81],
        [ 12,  48, 108]],

       [[  8,  32,  72],
        [ 12,  48, 108],
        [ 16,  64, 144]]])

array([[[  4,  16,  36],
        [  6,  24,  54],
        [  8,  32,  72]],

       [[  6,  24,  54],
        [  9,  36,  81],
        [ 12,  48, 108]],

       [[  8,  32,  72],
        [ 12,  48, 108],
        [ 16,  64, 144]]])